### ISSUE TITLE
Think about to migrate to gitlab.com 

### ISSUE THREAD

**Issue by stikstof** [rivm-syso/OPS#15]
Auto DevOps
It will automatically build, test, and deploy your application based on a predefined CI/CD configuration.

check: https://gitlab.com/AERIUS

**Comment by RIVM-OPS** [comment]
First of all, we'd like to apologise for the late reaction. We'll try to reply more quickly to future issues.
Thank you for your suggestion. The development of the OPS model takes place at an internal RIVM Gitlab server. CI/CD is being implemented there. Therefore, this issue will be closed.
