### ISSUE TITLE
Unnecessary personal details 

### ISSUE THREAD

**Issue by monty241** [rivm-syso/OPS#2]
The current release contains change notes with the names of persons no longer involved in developing and/or maintaining the code base. 

These are quite hard to remove completely thanks to git but maybe a good start would be to remove them from next release.

**Comment by monty241** [comment]
See for instance m_fileutils.f90

**Comment by monty241** [comment]
Largely applied in V5.0.0.

**Comment by jfjlaros** [comment]
Perhaps it would be better to distinguish between authors and maintainers. Removing the names of original authors is not a good practice if you ask me.

@RIVM-OPS You might want to reconsider reverting this.

**Comment by RIVM-OPS** [comment]
Beste Jeroen,

We zullen dit ter overweging meenemen in een volgend overleg.

Groet,
OPS-Support.

--
"Herinner je verleden, droom van morgen, maar leef vandaag!”
"What makes you different, makes you beautiful"
--

**Comment by RIVM-OPS** [comment]
We have decided not to include author names in the source code. Contributing authors are acknowledged in other documents.
