### ISSUE TITLE
Toevoegen achtergrond publiek maken model

### ISSUE THREAD

**Issue by monty241** [rivm-syso/OPS#28]
Voor beter begrip van de context zou het openbaar maken van het openbaarmaken van Aerius en OPS helpen.

Mogelijk is de oorzaak beschreven in https://uitspraken.rechtspraak.nl/inziendocument?id=ECLI:NL:RBDHA:2019:13779, maar mogelijk eerdere of latere besluiten, binnen RIVM, ministeries of rechter, hebben hiertoe geleid. Als buitenstaander is best lastig om de historie te bepalen op basis van nieuwsartikelen zoals https://www.omropfryslan.nl/nl/nieuws/927198/rechter-rivm-moet-rekenmodel-voor-stikstof-vrijgeven.

Daarnaast is er gezien het NRC-artikel https://www.nrc.nl/nieuws/2022/06/11/de-man-achter-het-model-waarmee-den-haag-stikstofberekeningen-doet-a4133158 blijkbaar enige verwarring over de rollen van Aerius en OPS in het berekeningsproces. Mogelijk is het handig om relatie met Aerius beter te belichten in de readme, zoals bijvoorbeeld beschreven in https://nl.wikipedia.org/wiki/AERIUS.

**Comment by Hilbrand** [comment]
In het [AERIUS handboek Calculator 2021](https://www.aerius.nl/nl/handboeken) is wel eea beschreven over relatie AERIUS/OPS. Misschien dat iets meer inzicht geeft.

**Comment by monty241** [comment]
Dat zou ook een goede kruisverwijzing zijn voor mensen die voor eerst OPS openen.

**Comment by RIVM-OPS** [comment]
Beste @monty241 ,
om de link tussen OPS en AERIUS duidelijker te maken hebben we nu een link naar de AERIUS website toegevoegd in de README. 
Om meer te vertellen over het proces van openbaar maken van OPS zullen we het een en ander moeten uitzoeken. Daar ligt op dit moment echter niet de prioriteit van de ontwikkelaars. Wellicht dat u via een andere weg hier meer over kunt leren.

**Comment by monty241** [comment]
Dank voor toevoegen link in README. 

Het beschrijven van de historische stappen die leiden tot openbaar maken is niet iets voor de ontwikkelaars, maar meer iets voor de Product Owner of communicatie. Als niet mogelijk, het zij zo, dit issue komt vanzelf ook wel op Google en dan kunnen mensen het aanvullen.
