### ISSUE TITLE
Create folder structure to improve overview

### ISSUE THREAD

**Issue by monty241** [rivm-syso/OPS#5]
Suggestion is to add a folder structure, such as:
* src for the f90 files
* test for test cases
* doc for documentation
etc.

**Comment by RIVM-OPS** [comment]
First of all, we'd like to apologise for the late reaction. We'll try to reply more quickly to future issues.
Thank you for your report. The folder structure will be changed in a future version of OPS, once that version has been released, this issue will be closed.

**Comment by RIVM-OPS** [comment]
In the latest release we have made a folder structure.
